services:
  db:
    container_name: postgres-clinique
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mhamed@1
      POSTGRES_DB: clinique_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  pgadmin:
    container_name: pgadmin4_Clinique
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mhamedaithssaine1@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Mhamed@1
    ports:
      - "8082:80"
volumes:
    db_data: